### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by lpil** [gleam-lang/httpc#13]
See the stdlib for examples

**Comment by Galaxy-Coding** [comment]
i can do it!

**Comment by lpil** [comment]
Wonderful, thank you!

**Comment by Galaxy-Coding** [comment]
@lpil do you mean something like this?
<img src="https://img.shields.io/badge/rust-%23000000.svg?&style=for-the-badge&logo=rust&logoColor=white"/>

**Comment by lpil** [comment]
![Screenshot_20201126-181030](https://user-images.githubusercontent.com/6134406/100382213-ba6a3800-3012-11eb-8075-b501487e4117.png)

Something like this from Gleam stdlib would be ideal https://github.com/gleam-lang/stdlib/

**Comment by Galaxy-Coding** [comment]
ok

**Comment by Galaxy-Coding** [comment]
where is the link to that repo/file?

**Comment by Galaxy-Coding** [comment]
<a href="https://github.com/gleam-lang/httpc/releases"><img src="https://img.shields.io/github/release/gleam-lang/httpc" alt="GitHub release"></a>
<a href="https://discord.gg/Fm8Pwmy"><img src="https://img.shields.io/discord/768594524158427167?color=blue" alt="Discord chat"></a>
![CI](https://github.com/gleam-lang/httpc/workflows/CI/badge.svg?branch=main)

**Comment by lpil** [comment]
Looks good @Galaxy-Coding , would you like to make a pull request adding these to the README.md file?

**Comment by Galaxy-Coding** [comment]
ok

**Comment by Galaxy-Coding** [comment]
just the workflow isn’t seeming right

**Comment by lpil** [comment]
Maybe like this?

```
![CI](https://github.com/gleam-lang/httpc/workflows/test/badge.svg?branch=main)
```
![CI](https://github.com/gleam-lang/httpc/workflows/test/badge.svg?branch=main)

**Comment by Galaxy-Coding** [comment]
![CI](https://github.com/gleam-lang/httpc/workflows/test/badge.svg?branch=main)

**Comment by Galaxy-Coding** [comment]
done. @lpil

**Comment by Galaxy-Coding** [comment]
When will i be able to see my changes?

**Comment by lpil** [comment]
Just merged your changes in! Should be there to see now. Thank you for your contribution
