### ISSUE TITLE
Unknown escape characters

### ISSUE THREAD

**Issue by syukronrm** [gleam-lang/httpc#17]
Compiling this project produce error:
```
> rebar3 compile
===> Verifying dependencies...

error: Syntax error
    ┌─ /home/me/projects/gleam/httpc/_build/default/lib/gleam_http/src/gleam/http.gleam:404:8
    │
404 │     <<"\s":utf8, _>> -> Error(Nil)
    │        ^ I don't understand this escape code

Hint: Add another backslash before it.
See: https://gleam.run/book/tour/strings.html#escape-sequences

===> Unable to compile Gleam project
```

Seems like the `\s` and `\c` escape characters are no longer supported. Well compiled after removing those characters.

**Environment:**
Gleam: gleam 0.15.0-dev

**Comment by lpil** [comment]
If you upgrade to the latest version of the HTTP library this will work. I'll upgrade this library shortly to make it the default 👍
