### ISSUE TITLE
Support for verify_none for TLS certs

### ISSUE THREAD

**Issue by hah** [gleam-lang/httpc#27]
👋, would like to have an option to ignore TLS certificate check.

It is useful if you're using a MITM proxy for debugging, however in my case Phillips hue's V2 api runs on the local network behind https, which is causing this error
```
TLS client: In state certify at ssl_handshake.erl:2132 generated CLIENT ALERT: Fatal - Bad Certificate
```

thanks a lot

**Comment by lpil** [comment]
Hello! I've added an API for this. I'm sorry this took so long, my inbox is swamped!
