### ISSUE TITLE
Unknown variable req

### ISSUE THREAD

**Issue by wilsonsilva** [gleam-lang/httpc#9]
I am just getting started with Gleam, coming from a Ruby background, and I want to create a program to download events from Bugsnag via their API. So I installed httpc and I tried to compile the exact source code in this library's readme using `rebar3 compile` and `gleam build`. I got the following error:

```
error: Unknown variable
   ┌─ /Users/wilson/projects/gleam/bugsnag_downloader/src/bugsnag_downloader.gleam:14:25
   │
14 │   try resp = httpc.send(req)
   │                         ^^^ did you mean `Get`?

The name `req` is not in scope here.
```

This is my deps config:

```
{deps, [
    {gleam_httpc, "0.1.1"},
    {gleam_stdlib, "0.11.0"},
    {gleam_otp, "0.1.0"}
]}.
```

I'm using Gleam `0.12.0` and Erlang `23.1.2`

**Comment by wilsonsilva** [comment]
Fixed in https://github.com/gleam-lang/httpc/pull/10

**Comment by lpil** [comment]
Oh dear! Thanks for finding this one. First impressions make a big difference
